name: build

on:
  push:
  pull_request:
  schedule:
    # Run regularly with fresh data
    - cron: '0 6,18 * * *'

env:
  FORCE_COLOR: 3

jobs:

  ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - run: sudo apt-get update -qq
    - run: sudo apt-get install -qq -y --no-install-recommends coinor-cbc
    - run: pip install --upgrade pipenv wheel
    - run: pipenv install --dev
    - run: pipenv run pytest -n auto
