name: build

on: [push, pull_request]

jobs:

  ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt-install
      run: sudo apt-get install -qq -y --no-install-recommends $(cat packages.txt)
    - name: pip-install
      run: pip install --upgrade pipenv wheel
    - name: pytest
      run: pipenv run pytest
